descriptor-schema-version: "2.7"
info:
  name: mlabbe/iperf3
  version: latest
app:
  cpuarch: x86_64
  env:
    PATH: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
  resources:
    cpu: "400"
    memory: "128"
    network:
    - interface-name: eth0
      ports:
        tcp:
        - "5201"
        udp:
        - "5201"
    profile: custom
  startup:
    args:
    - -s
    rootfs: rootfs.tar
    target:
    - iperf3
    user: iperf
  type: docker
